# Generated by Django 2.2.4 on 2020-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iflogged', models.BooleanField(default=False)),
                ('curr_name', models.CharField(default='hh', max_length=200)),
                ('curr_email', models.CharField(default='hh@hhh.com', max_length=200)),
                ('ifTeacher', models.BooleanField(default=False)),
            ],
        ),
    ]
